import jsPDF from 'jspdf';
import { AnalysisResult } from './gemini';

export function generateAnalysisReport(
  projectName: string,
  analysis: AnalysisResult,
  userEmail: string
): jsPDF {
  const doc = new jsPDF();
  let yPosition = 20;
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);

  // Set default font to ensure proper encoding
  doc.setFont('helvetica', 'normal');

  // Helper function to safely encode text
  const safeText = (text: string): string => {
    if (!text) return '';
    return text
      .toString()
      .replace(/[^\x20-\x7E]/g, '') // Keep only printable ASCII characters
      .replace(/[""]/g, '"') // Replace smart quotes
      .replace(/['']/g, "'") // Replace smart apostrophes
      .replace(/[–—]/g, '-') // Replace em/en dashes
      .replace(/…/g, '...') // Replace ellipsis
      .trim();
  };

  // Helper function to add new page if needed
  const checkPageBreak = (height: number) => {
    if (yPosition + height > pageHeight - margin - 30) {
      doc.addPage();
      yPosition = 30;
      addWatermark();
    }
  };

  // Add watermark to each page
  const addWatermark = () => {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(160, 160, 160);
    doc.text('Generated by Lint - Professional Code Analysis', pageWidth / 2, pageHeight - 10, { align: 'center' });
  };

  // Add professional header
  const addHeader = () => {
    // Header background gradient
    doc.setFillColor(59, 130, 246);
    doc.rect(0, 0, pageWidth, 50, 'F');
    
    doc.setFillColor(147, 51, 234);
    doc.rect(pageWidth * 0.7, 0, pageWidth * 0.3, 50, 'F');
    
    // Modern logo
    doc.setFillColor(255, 255, 255);
    doc.circle(margin + 15, 30, 12, 'F');
    doc.setFillColor(59, 130, 246);
    doc.circle(margin + 15, 30, 9, 'F');
    doc.setFillColor(255, 255, 255);
    doc.circle(margin + 15, 30, 4, 'F');
    
    // Title
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('Lint', margin + 35, 28);
    
    // Subtitle
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Professional Code Analysis Report', margin + 35, 40);
    
    yPosition = 65;
  };

  // Add section header
  const addSectionHeader = (title: string, color: [number, number, number] = [59, 130, 246]) => {
    checkPageBreak(35);
    
    yPosition += 15;
    
    // Section background
    doc.setFillColor(color[0], color[1], color[2], 0.1);
    doc.rect(margin, yPosition - 10, contentWidth, 25, 'F');
    
    // Left accent bar
    doc.setFillColor(color[0], color[1], color[2]);
    doc.rect(margin, yPosition - 10, 4, 25, 'F');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(color[0], color[1], color[2]);
    doc.text(safeText(title), margin + 12, yPosition + 5);
    
    yPosition += 30;
  };

  // Add info box
  const addInfoBox = (label: string, value: string) => {
    checkPageBreak(20);
    
    // Card background
    doc.setFillColor(249, 250, 251);
    doc.rect(margin, yPosition, contentWidth, 18, 'F');
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.5);
    doc.rect(margin, yPosition, contentWidth, 18);
    
    // Left accent
    doc.setFillColor(59, 130, 246);
    doc.rect(margin, yPosition, 3, 18, 'F');
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(75, 85, 99);
    doc.text(safeText(label) + ':', margin + 10, yPosition + 11);
    
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text(safeText(value), margin + 70, yPosition + 11);
    
    yPosition += 25;
  };

  // Add score card
  const addScoreCard = (score: number, title: string) => {
    checkPageBreak(50);
    
    const scoreColor = score > 70 ? [239, 68, 68] : 
                     score > 40 ? [245, 158, 11] : 
                     [34, 197, 94];
    
    // Card background
    doc.setFillColor(255, 255, 255);
    doc.rect(margin, yPosition, contentWidth, 45, 'F');
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.5);
    doc.rect(margin, yPosition, contentWidth, 45);
    
    // Score circle
    const circleX = margin + 35;
    const circleY = yPosition + 22;
    const radius = 16;
    
    doc.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2], 0.1);
    doc.circle(circleX, circleY, radius, 'F');
    doc.setDrawColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.setLineWidth(3);
    doc.circle(circleX, circleY, radius);
    
    // Score text
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.text(score.toString(), circleX, circleY + 4, { align: 'center' });
    
    // Title
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(31, 41, 55);
    doc.text(safeText(title), margin + 65, yPosition + 20);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text('Lower scores indicate better code quality', margin + 65, yPosition + 32);
    
    yPosition += 60;
  };

  // Start document
  addHeader();
  addWatermark();

  // Project Information
  addSectionHeader('Project Information', [59, 130, 246]);
  addInfoBox('Project Name', safeText(projectName));
  addInfoBox('Generated On', new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  }));
  addInfoBox('Generated For', safeText(userEmail));
  addInfoBox('Analysis Engine', 'Gemini 2.0 Flash AI');

  // Overall Score
  addSectionHeader('Overall Assessment', [147, 51, 234]);
  addScoreCard(analysis.overall_debt_score, 'Technical Debt Score');

  // Executive Summary
  if (analysis.summary) {
    addSectionHeader('Executive Summary', [16, 185, 129]);
    checkPageBreak(40);
    
    const cleanSummary = safeText(analysis.summary);
    const summaryLines = doc.splitTextToSize(cleanSummary, contentWidth - 30);
    const summaryHeight = summaryLines.length * 7 + 25;
    
    doc.setFillColor(249, 250, 251);
    doc.rect(margin, yPosition, contentWidth, summaryHeight, 'F');
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.5);
    doc.rect(margin, yPosition, contentWidth, summaryHeight);
    
    // Left accent
    doc.setFillColor(16, 185, 129);
    doc.rect(margin, yPosition, 4, summaryHeight, 'F');
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(55, 65, 81);
    
    summaryLines.forEach((line: string, index: number) => {
      checkPageBreak(10);
      doc.text(safeText(line), margin + 15, yPosition + 18 + (index * 7));
    });
    
    yPosition += summaryHeight + 20;
  }

  // File Analysis
  if (analysis.file_analyses.length > 0) {
    addSectionHeader('Detailed File Analysis', [245, 158, 11]);
    
    analysis.file_analyses.slice(0, 10).forEach((fileAnalysis, index) => {
      checkPageBreak(50);
      
      // File header
      doc.setFillColor(255, 255, 255);
      doc.rect(margin, yPosition, contentWidth, 30, 'F');
      doc.setDrawColor(229, 231, 235);
      doc.setLineWidth(0.5);
      doc.rect(margin, yPosition, contentWidth, 30);
      
      // File icon
      doc.setFillColor(59, 130, 246);
      doc.rect(margin + 10, yPosition + 10, 12, 12, 'F');
      doc.setFillColor(255, 255, 255);
      doc.rect(margin + 11, yPosition + 11, 10, 10, 'F');
      
      // File name
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(31, 41, 55);
      const fileName = fileAnalysis.file_path.length > 50 ? 
        '...' + fileAnalysis.file_path.slice(-47) : 
        fileAnalysis.file_path;
      doc.text(safeText(fileName), margin + 30, yPosition + 16);
      
      // File score
      const fileScoreColor = fileAnalysis.debt_score > 70 ? [239, 68, 68] :
                            fileAnalysis.debt_score > 40 ? [245, 158, 11] :
                            [34, 197, 94];
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(fileScoreColor[0], fileScoreColor[1], fileScoreColor[2]);
      doc.text(`Score: ${fileAnalysis.debt_score}/100`, margin + 30, yPosition + 26);
      
      yPosition += 35;
      
      // Issues
      if (fileAnalysis.issues && fileAnalysis.issues.length > 0) {
        fileAnalysis.issues.slice(0, 3).forEach((issue: any) => {
          checkPageBreak(40);
          
          const severityColor = issue.severity === 'high' ? [239, 68, 68] :
                               issue.severity === 'medium' ? [245, 158, 11] :
                               [156, 163, 175];
          
          // Issue card
          doc.setFillColor(248, 250, 252);
          doc.rect(margin + 10, yPosition, contentWidth - 20, 25, 'F');
          doc.setDrawColor(severityColor[0], severityColor[1], severityColor[2]);
          doc.setLineWidth(0.5);
          doc.rect(margin + 10, yPosition, contentWidth - 20, 25);
          
          // Severity indicator
          doc.setFillColor(severityColor[0], severityColor[1], severityColor[2]);
          doc.circle(margin + 20, yPosition + 10, 4, 'F');
          
          // Issue type
          doc.setFontSize(10);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(severityColor[0], severityColor[1], severityColor[2]);
          const issueType = safeText(issue.type || 'Code Issue');
          const severity = safeText(issue.severity || 'medium');
          doc.text(`${issueType} (${severity})`, margin + 30, yPosition + 10);
          
          // Description
          doc.setFontSize(9);
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(75, 85, 99);
          const cleanDescription = safeText(issue.description || 'No description available');
          const descLines = doc.splitTextToSize(cleanDescription, contentWidth - 50);
          descLines.slice(0, 1).forEach((line: string, lineIndex: number) => {
            checkPageBreak(8);
            doc.text(safeText(line), margin + 30, yPosition + 18 + (lineIndex * 6));
          });
          
          yPosition += 30;
          
          // Suggestion
          if (issue.suggestion) {
            checkPageBreak(15);
            doc.setFontSize(9);
            doc.setTextColor(59, 130, 246);
            doc.setFont('helvetica', 'bold');
            doc.text('Suggestion: ', margin + 30, yPosition);
            
            doc.setFont('helvetica', 'normal');
            const cleanSuggestion = safeText(issue.suggestion);
            const suggestionLines = doc.splitTextToSize(cleanSuggestion, contentWidth - 70);
            suggestionLines.slice(0, 1).forEach((line: string, lineIndex: number) => {
              checkPageBreak(7);
              doc.text(safeText(line), margin + 75, yPosition + (lineIndex * 6));
            });
            
            yPosition += 12;
          }
          
          yPosition += 10;
        });
      }
      
      yPosition += 15;
    });
  }

  // Recommendations
  if (analysis.recommendations.length > 0) {
    addSectionHeader('Priority Recommendations', [34, 197, 94]);
    
    analysis.recommendations.forEach((rec: any, index: number) => {
      checkPageBreak(45);
      
      const priorityColor = rec.priority === 'high' ? [239, 68, 68] :
                           rec.priority === 'medium' ? [245, 158, 11] :
                           [34, 197, 94];
      
      // Recommendation card
      const cardHeight = 35;
      doc.setFillColor(255, 255, 255);
      doc.rect(margin, yPosition, contentWidth, cardHeight, 'F');
      doc.setDrawColor(priorityColor[0], priorityColor[1], priorityColor[2]);
      doc.setLineWidth(0.8);
      doc.rect(margin, yPosition, contentWidth, cardHeight);
      
      // Priority bar
      doc.setFillColor(priorityColor[0], priorityColor[1], priorityColor[2]);
      doc.rect(margin, yPosition, 5, cardHeight, 'F');
      
      // Priority badge
      doc.setFillColor(priorityColor[0], priorityColor[1], priorityColor[2], 0.1);
      doc.rect(margin + 15, yPosition + 8, 30, 10, 'F');
      
      // Category
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(31, 41, 55);
      const category = safeText(rec.category || 'General');
      doc.text(category, margin + 55, yPosition + 15);
      
      // Priority text
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(priorityColor[0], priorityColor[1], priorityColor[2]);
      const priority = safeText(rec.priority || 'medium').toUpperCase();
      doc.text(`${priority} PRIORITY`, margin + 17, yPosition + 15);
      
      yPosition += cardHeight + 8;
      
      // Description
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(75, 85, 99);
      const cleanDescription = safeText(rec.description || 'No description available');
      const descLines = doc.splitTextToSize(cleanDescription, contentWidth - 20);
      descLines.slice(0, 2).forEach((line: string, lineIndex: number) => {
        checkPageBreak(8);
        doc.text(safeText(line), margin + 10, yPosition + (lineIndex * 7));
      });
      yPosition += Math.min(descLines.length, 2) * 7 + 8;
      
      // Impact
      if (rec.impact) {
        checkPageBreak(15);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(107, 114, 128);
        doc.text('Impact: ', margin + 10, yPosition);
        
        doc.setFont('helvetica', 'normal');
        const cleanImpact = safeText(rec.impact);
        const impactLines = doc.splitTextToSize(cleanImpact, contentWidth - 40);
        impactLines.slice(0, 1).forEach((line: string, lineIndex: number) => {
          checkPageBreak(6);
          doc.text(safeText(line), margin + 40, yPosition + (lineIndex * 6));
        });
        yPosition += 12;
      }
      
      yPosition += 20;
    });
  }

  // Professional footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Footer background
    doc.setFillColor(249, 250, 252);
    doc.rect(0, pageHeight - 25, pageWidth, 25, 'F');
    
    // Footer line
    doc.setDrawColor(59, 130, 246);
    doc.setLineWidth(0.5);
    doc.line(0, pageHeight - 25, pageWidth, pageHeight - 25);
    
    // Footer content
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text('Generated by Lint | Professional Code Analysis Platform', 
             margin, pageHeight - 16);
    
    doc.setTextColor(156, 163, 175);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 16, { align: 'right' });
    
    // Powered by
    doc.setFontSize(7);
    doc.setTextColor(59, 130, 246);
    doc.text('Powered by Walmart Innovation - Sparkathon', 
             pageWidth / 2, pageHeight - 8, { align: 'center' });
  }

  return doc;
}