import jsPDF from 'jspdf';
import { AnalysisResult } from './gemini';

export function generateAnalysisReport(
  projectName: string,
  analysis: AnalysisResult,
  userEmail: string
): jsPDF {
  const doc = new jsPDF();
  let yPosition = 20;
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);

  // Set default font to ensure proper encoding
  doc.setFont('helvetica', 'normal');

  // Helper function to safely encode text
  const safeText = (text: string): string => {
    if (!text) return '';
    return text
      .toString()
      .replace(/[^\x20-\x7E]/g, '') // Keep only printable ASCII characters
      .replace(/[""]/g, '"') // Replace smart quotes
      .replace(/['']/g, "'") // Replace smart apostrophes
      .replace(/[–—]/g, '-') // Replace em/en dashes
      .replace(/…/g, '...') // Replace ellipsis
      .trim();
  };

  // Helper function to add new page if needed
  const checkPageBreak = (height: number) => {
    if (yPosition + height > pageHeight - margin - 30) {
      doc.addPage();
      yPosition = 30;
      addWatermark();
    }
  };

  // Add watermark to each page
  const addWatermark = () => {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(160, 160, 160);
    doc.text('Generated by Lint - Professional Code Analysis', pageWidth / 2, pageHeight - 10, { align: 'center' });
  };

  // Add professional header
  const addHeader = () => {
    // Header background gradient
    doc.setFillColor(59, 130, 246);
    doc.rect(0, 0, pageWidth, 50, 'F');
    
    doc.setFillColor(147, 51, 234);
    doc.rect(pageWidth * 0.7, 0, pageWidth * 0.3, 50, 'F');
    
    // Modern logo
    doc.setFillColor(255, 255, 255);
    doc.circle(margin + 15, 30, 12, 'F');
    doc.setFillColor(59, 130, 246);
    doc.circle(margin + 15, 30, 9, 'F');
    doc.setFillColor(255, 255, 255);
    doc.circle(margin + 15, 30, 4, 'F');
    
    // Title
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('Lint', margin + 35, 28);
    
    // Subtitle
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Professional Code Analysis Report', margin + 35, 40);
    
    yPosition = 65;
  };

  // Add section header
  const addSectionHeader = (title: string, color: [number, number, number] = [59, 130, 246]) => {
    checkPageBreak(35);
    
    yPosition += 15;
    
    // Section background
    doc.setFillColor(color[0], color[1], color[2], 0.1);
    doc.rect(margin, yPosition - 10, contentWidth, 25, 'F');
    
    // Left accent bar
    doc.setFillColor(color[0], color[1], color[2]);
    doc.rect(margin, yPosition - 10, 4, 25, 'F');
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(color[0], color[1], color[2]);
    doc.text(safeText(title), margin + 12, yPosition + 5);
    
    yPosition += 30;
  };

  // Add info box
  const addInfoBox = (label: string, value: string) => {
    checkPageBreak(20);
    
    // Card background
    doc.setFillColor(249, 250, 251);
    doc.rect(margin, yPosition, contentWidth, 18, 'F');
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.5);
    doc.rect(margin, yPosition, contentWidth, 18);
    
    // Left accent
    doc.setFillColor(59, 130, 246);
    doc.rect(margin, yPosition, 3, 18, 'F');
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(75, 85, 99);
    doc.text(safeText(label) + ':', margin + 10, yPosition + 11);
    
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text(safeText(value), margin + 70, yPosition + 11);
    
    yPosition += 25;
  };

  // Add score card
  const addScoreCard = (score: number, title: string) => {
    checkPageBreak(50);
    
    const scoreColor = score > 70 ? [239, 68, 68] : 
                     score > 40 ? [245, 158, 11] : 
                     [34, 197, 94];
    
    // Card background
    doc.setFillColor(255, 255, 255);
    doc.rect(margin, yPosition, contentWidth, 45, 'F');
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.5);
    doc.rect(margin, yPosition, contentWidth, 45);
    
    // Score circle
    const circleX = margin + 35;
    const circleY = yPosition + 22;
    const radius = 16;
    
    doc.setFillColor(scoreColor[0], scoreColor[1], scoreColor[2], 0.1);
    doc.circle(circleX, circleY, radius, 'F');
    doc.setDrawColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.setLineWidth(3);
    doc.circle(circleX, circleY, radius);
    
    // Score text
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.text(score.toString(), circleX, circleY + 4, { align: 'center' });
    
    // Title
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(31, 41, 55);
    doc.text(safeText(title), margin + 65, yPosition + 20);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text('Lower scores indicate better code quality', margin + 65, yPosition + 32);
    
    yPosition += 60;
  };

  // Add file analysis card with proper container
  const addFileAnalysisCard = (fileAnalysis: any) => {
    // Calculate total height needed for this file
    const issueCount = Math.min(fileAnalysis.issues?.length || 0, 3);
    const estimatedHeight = 50 + (issueCount * 35) + 20; // Header + issues + padding
    
    checkPageBreak(estimatedHeight);
    
    const startY = yPosition;
    
    // Main file container
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(1);
    
    // File header section
    const headerHeight = 40;
    doc.rect(margin, yPosition, contentWidth, headerHeight, 'FD');
    
    // Header background with subtle gradient effect
    doc.setFillColor(248, 250, 252);
    doc.rect(margin + 1, yPosition + 1, contentWidth - 2, headerHeight - 2, 'F');
    
    // Left accent bar for file
    doc.setFillColor(59, 130, 246);
    doc.rect(margin, yPosition, 4, headerHeight, 'F');
    
    // File icon container
    const iconX = margin + 15;
    const iconY = yPosition + 12;
    doc.setFillColor(59, 130, 246);
    doc.roundedRect(iconX, iconY, 16, 16, 2, 2, 'F');
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(iconX + 2, iconY + 2, 12, 12, 1, 1, 'F');
    
    // File name
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(31, 41, 55);
    const fileName = fileAnalysis.file_path.length > 45 ? 
      '...' + fileAnalysis.file_path.slice(-42) : 
      fileAnalysis.file_path;
    doc.text(safeText(fileName), iconX + 25, yPosition + 18);
    
    // File score badge
    const fileScoreColor = fileAnalysis.debt_score > 70 ? [239, 68, 68] :
                          fileAnalysis.debt_score > 40 ? [245, 158, 11] :
                          [34, 197, 94];
    
    // Score badge background
    const badgeX = pageWidth - margin - 80;
    const badgeY = yPosition + 10;
    doc.setFillColor(fileScoreColor[0], fileScoreColor[1], fileScoreColor[2], 0.1);
    doc.roundedRect(badgeX, badgeY, 70, 20, 10, 10, 'F');
    doc.setDrawColor(fileScoreColor[0], fileScoreColor[1], fileScoreColor[2]);
    doc.setLineWidth(1);
    doc.roundedRect(badgeX, badgeY, 70, 20, 10, 10, 'D');
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(fileScoreColor[0], fileScoreColor[1], fileScoreColor[2]);
    doc.text(`Score: ${fileAnalysis.debt_score}/100`, badgeX + 35, badgeY + 13, { align: 'center' });
    
    yPosition += headerHeight + 5;
    
    // Issues container
    if (fileAnalysis.issues && fileAnalysis.issues.length > 0) {
      const issues = fileAnalysis.issues.slice(0, 3);
      
      issues.forEach((issue: any, issueIndex: number) => {
        const severityColor = issue.severity === 'high' ? [239, 68, 68] :
                             issue.severity === 'medium' ? [245, 158, 11] :
                             [34, 197, 94];
        
        // Issue container
        const issueHeight = 30;
        doc.setFillColor(250, 251, 252);
        doc.rect(margin + 10, yPosition, contentWidth - 20, issueHeight, 'F');
        doc.setDrawColor(severityColor[0], severityColor[1], severityColor[2], 0.3);
        doc.setLineWidth(0.5);
        doc.rect(margin + 10, yPosition, contentWidth - 20, issueHeight, 'D');
        
        // Left severity indicator
        doc.setFillColor(severityColor[0], severityColor[1], severityColor[2]);
        doc.rect(margin + 10, yPosition, 3, issueHeight, 'F');
        
        // Severity icon (circle)
        doc.setFillColor(severityColor[0], severityColor[1], severityColor[2]);
        doc.circle(margin + 25, yPosition + 10, 4, 'F');
        
        // Issue type and severity
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(severityColor[0], severityColor[1], severityColor[2]);
        const issueType = safeText(issue.type || 'Code Issue');
        const severity = safeText(issue.severity || 'medium');
        doc.text(`${issueType} (${severity})`, margin + 35, yPosition + 10);
        
        // Issue description
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(75, 85, 99);
        const cleanDescription = safeText(issue.description || 'No description available');
        const descLines = doc.splitTextToSize(cleanDescription, contentWidth - 80);
        const displayLine = descLines[0] || '';
        doc.text(safeText(displayLine), margin + 35, yPosition + 20);
        
        yPosition += issueHeight + 3;
        
        // Suggestion container (if exists)
        if (issue.suggestion) {
          const suggestionHeight = 18;
          doc.setFillColor(239, 246, 255);
          doc.rect(margin + 15, yPosition, contentWidth - 30, suggestionHeight, 'F');
          doc.setDrawColor(59, 130, 246, 0.3);
          doc.setLineWidth(0.5);
          doc.rect(margin + 15, yPosition, contentWidth - 30, suggestionHeight, 'D');
          
          // Suggestion icon
          doc.setFillColor(59, 130, 246);
          doc.circle(margin + 25, yPosition + 9, 3, 'F');
          
          doc.setFontSize(8);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(59, 130, 246);
          doc.text('Suggestion:', margin + 35, yPosition + 9);
          
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(75, 85, 99);
          const cleanSuggestion = safeText(issue.suggestion);
          const suggestionLines = doc.splitTextToSize(cleanSuggestion, contentWidth - 90);
          const displaySuggestion = suggestionLines[0] || '';
          doc.text(safeText(displaySuggestion), margin + 75, yPosition + 9);
          
          yPosition += suggestionHeight + 3;
        }
      });
    }
    
    // Bottom border for the entire file container
    const totalHeight = yPosition - startY;
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(1);
    doc.rect(margin, startY, contentWidth, totalHeight, 'D');
    
    yPosition += 15; // Space between files
  };

  // Start document
  addHeader();
  addWatermark();

  // Project Information
  addSectionHeader('Project Information', [59, 130, 246]);
  addInfoBox('Project Name', safeText(projectName));
  addInfoBox('Generated On', new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  }));
  addInfoBox('Generated For', safeText(userEmail));
  addInfoBox('Analysis Engine', 'Gemini 2.0 Flash AI');

  // Overall Score
  addSectionHeader('Overall Assessment', [147, 51, 234]);
  addScoreCard(analysis.overall_debt_score, 'Technical Debt Score');

  // Executive Summary
  if (analysis.summary) {
    addSectionHeader('Executive Summary', [16, 185, 129]);
    checkPageBreak(40);
    
    const cleanSummary = safeText(analysis.summary);
    const summaryLines = doc.splitTextToSize(cleanSummary, contentWidth - 30);
    const summaryHeight = summaryLines.length * 7 + 25;
    
    doc.setFillColor(249, 250, 251);
    doc.rect(margin, yPosition, contentWidth, summaryHeight, 'F');
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.5);
    doc.rect(margin, yPosition, contentWidth, summaryHeight);
    
    // Left accent
    doc.setFillColor(16, 185, 129);
    doc.rect(margin, yPosition, 4, summaryHeight, 'F');
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(55, 65, 81);
    
    summaryLines.forEach((line: string, index: number) => {
      checkPageBreak(10);
      doc.text(safeText(line), margin + 15, yPosition + 18 + (index * 7));
    });
    
    yPosition += summaryHeight + 20;
  }

  // File Analysis with redesigned containers
  if (analysis.file_analyses.length > 0) {
    addSectionHeader('Detailed File Analysis', [245, 158, 11]);
    
    // Add section description
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text('Individual file analysis with identified issues and recommendations', margin, yPosition);
    yPosition += 20;
    
    analysis.file_analyses.slice(0, 8).forEach((fileAnalysis, index) => {
      addFileAnalysisCard(fileAnalysis);
    });
  }

  // Recommendations
  if (analysis.recommendations.length > 0) {
    addSectionHeader('Priority Recommendations', [34, 197, 94]);
    
    analysis.recommendations.forEach((rec: any, index: number) => {
      checkPageBreak(45);
      
      const priorityColor = rec.priority === 'high' ? [239, 68, 68] :
                           rec.priority === 'medium' ? [245, 158, 11] :
                           [34, 197, 94];
      
      // Recommendation card
      const cardHeight = 35;
      doc.setFillColor(255, 255, 255);
      doc.rect(margin, yPosition, contentWidth, cardHeight, 'F');
      doc.setDrawColor(priorityColor[0], priorityColor[1], priorityColor[2]);
      doc.setLineWidth(0.8);
      doc.rect(margin, yPosition, contentWidth, cardHeight);
      
      // Priority bar
      doc.setFillColor(priorityColor[0], priorityColor[1], priorityColor[2]);
      doc.rect(margin, yPosition, 5, cardHeight, 'F');
      
      // Priority badge
      doc.setFillColor(priorityColor[0], priorityColor[1], priorityColor[2], 0.1);
      doc.rect(margin + 15, yPosition + 8, 30, 10, 'F');
      
      // Category
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(31, 41, 55);
      const category = safeText(rec.category || 'General');
      doc.text(category, margin + 55, yPosition + 15);
      
      // Priority text
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(priorityColor[0], priorityColor[1], priorityColor[2]);
      const priority = safeText(rec.priority || 'medium').toUpperCase();
      doc.text(`${priority} PRIORITY`, margin + 17, yPosition + 15);
      
      yPosition += cardHeight + 8;
      
      // Description
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(75, 85, 99);
      const cleanDescription = safeText(rec.description || 'No description available');
      const descLines = doc.splitTextToSize(cleanDescription, contentWidth - 20);
      descLines.slice(0, 2).forEach((line: string, lineIndex: number) => {
        checkPageBreak(8);
        doc.text(safeText(line), margin + 10, yPosition + (lineIndex * 7));
      });
      yPosition += Math.min(descLines.length, 2) * 7 + 8;
      
      // Impact
      if (rec.impact) {
        checkPageBreak(15);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(107, 114, 128);
        doc.text('Impact: ', margin + 10, yPosition);
        
        doc.setFont('helvetica', 'normal');
        const cleanImpact = safeText(rec.impact);
        const impactLines = doc.splitTextToSize(cleanImpact, contentWidth - 40);
        impactLines.slice(0, 1).forEach((line: string, lineIndex: number) => {
          checkPageBreak(6);
          doc.text(safeText(line), margin + 40, yPosition + (lineIndex * 6));
        });
        yPosition += 12;
      }
      
      yPosition += 20;
    });
  }

  // Professional footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Footer background
    doc.setFillColor(249, 250, 252);
    doc.rect(0, pageHeight - 25, pageWidth, 25, 'F');
    
    // Footer line
    doc.setDrawColor(59, 130, 246);
    doc.setLineWidth(0.5);
    doc.line(0, pageHeight - 25, pageWidth, pageHeight - 25);
    
    // Footer content
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text('Generated by Lint | Professional Code Analysis Platform', 
             margin, pageHeight - 16);
    
    doc.setTextColor(156, 163, 175);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 16, { align: 'right' });
    
    // Powered by
    doc.setFontSize(7);
    doc.setTextColor(59, 130, 246);
    doc.text('Powered by Walmart Innovation - Sparkathon', 
             pageWidth / 2, pageHeight - 8, { align: 'center' });
  }

  return doc;
}